✨ feat(staticroutes): adds v2 static routes
rapyuta-robotics/rapyuta-io-cli pull request #181
Opened 2023-06-26 07:05 UTC by RomilShah

This commit introduces support for V2 static routes

[![asciicast](https://asciinema.org/a/599491.svg)](https://asciinema.org/a/599491)

2023-07-11 08:15 UTC, pallabpain approved these changes

2023-07-29 18:30 UTC, pallabpain commented on riocli/static_route/model.py
>              'nameOrGUID': self.metadata.name
The code in this file should use the v2 static route APIs instead of the v1 APIs.

2023-08-18 11:42 UTC, pallabpain requested changes

2023-08-18 11:42 UTC, pallabpain commented on riocli/static_route/model.py
> +        import pdb;pdb.set_trace()
Remove this line.

2023-08-18 12:04 UTC, ankitrgadiya requested changes

2023-08-18 12:04 UTC, ankitrgadiya commented on riocli/static_route/model.py
> +        static_route.pop("rc", None)
```suggestion
        static_route.pop("rc", None)
        static_route = unmunchify(self)
```

2023-08-18 12:04 UTC, ankitrgadiya commented on riocli/static_route/util.py
>  def name_to_guid(f: typing.Callable) -> typing.Callable:
We can remove these functions as now our API supports Name directly.

2023-08-21 09:06 UTC, ankitrgadiya requested changes

2023-08-21 09:06 UTC, ankitrgadiya commented on riocli/static_route/util.py
>  def get_static_route_name(client: Client, guid: str) -> str:
todo: This function is not used anywhere. We can remove this as well.

2023-08-21 13:51 UTC, pallabpain requested changes

2023-08-21 13:51 UTC, pallabpain commented on riocli/static_route/util.py
> +    static_route = client.get_static_route(name)
This still uses the v1 client. Please use the v2 client here. You can omit using the passed client and redefine the client inside the function to use the v2 client which makes it easy to get route by name.

2023-08-22 10:14 UTC, pallabpain approved these changes

2023-08-24 04:48 UTC, pallabpain commented on riocli/apply/resolver.py
> +            "staticroute": self.v2client.list_static_routes,
@RomilShah There's one more function above this, `guid_functor`. Update that as well.

2023-08-28 05:56 UTC, ankitrgadiya approved these changes

2023-08-28 06:00 UTC, pallabpain approved these changes

2023-08-28 06:06 UTC, merged