fix(deployment): made dependent deployment ready phase to provisioning
rapyuta-robotics/rapyuta-io-cli pull request #204
Opened 2023-07-24 17:11 UTC by smrutisenapati

2023-07-25 02:01 UTC, pallabpain approved these changes

2023-07-25 02:02 UTC, pallabpain requested changes
@smrutisenapati Can you reword the commit message?
```
fix(deployment): sets dependent deployment ready phase to PROVISIONING
```

2023-07-27 02:41 UTC, amitsingh21 approved these changes

2023-07-27 05:56 UTC, pallabpain approved these changes

2023-07-27 07:15 UTC, pallabpain approved these changes

2023-07-27 07:28 UTC, merged