feat(package): add support for nested docker images.
rapyuta-robotics/rapyuta-io-cli pull request #248
Opened 2023-12-22 07:32 UTC by ankitrgadiya

Examples:
quay.io/rapyuta/flaptter/flaptter_runtime:0.0.1

2023-12-24 10:15 UTC, smrutisenapati approved these changes

2024-01-08 03:25 UTC, pallabpain approved these changes

2024-01-19 07:02 UTC, pallabpain requested changes
Looks good.

2024-01-19 07:02 UTC, pallabpain commented on setup.py
> +        "rapyuta-io @ git+https://github.com/rapyuta-robotics/rapyuta-io-sdk@fix/flaptter-support#egg=rapyuta_io",
todo: Revert this once SDK is updated and released.

2024-01-22 04:41 UTC, pallabpain approved these changes

2024-01-22 05:03 UTC, merged