Fix/multiple bugs
rapyuta-robotics/rapyuta-io-cli pull request #250
Opened 2024-01-16 11:05 UTC by RomilShah

Test manifests:

```
---
apiVersion: apiextensions.rapyuta.io/v1
kind: Package
metadata:
  description: Sootballs Printer Cups package
  labels:
    app: printer_cups
  name: sootballs_printer_cups
  version: 2.0.1-kokubu
spec:
  device:
    arch: amd64
    restart: always
  executables:
  - docker:
      image: nginx
    name: cups
    runAsBash: false
    type: docker
  runtime: device
#---
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  depends:
    kind: package
    nameOrGUID: pkg-oytmqdbzeajwyxsgczeawfzd
    version: 2.0.1-kokubu
  labels:
    app: printer_cups
  name: sootballs_printer_cups
spec:
  device:
    depends:
      kind: device
      nameOrGUID: romil-v3
  runtime: device
  volumes:
  - execName: cups
    mountPath: /etc/cups/printers.conf
    subPath: /opt/rapyuta/configs/cups/printers.conf
#    depends: #not for device
#      kind: disk
#      nameOrGUID: "romil"

```

2024-01-16 17:53 UTC, pallabpain requested changes

2024-01-16 17:53 UTC, pallabpain commented on riocli/device/delete.py
> +                spinner_text = click.style('{} device(s) deleted successfully.'.format(len(devices)), Colors.GREEN)
Let's just keep this instead.
```suggestion
            spinner_text = click.style('{} device(s) deleted successfully.'.format(len(devices)), Colors.GREEN)
```

nit: Please correct the scope for this commit
```
fix(device): improves message when devices deleted successfully
```

2024-01-16 17:53 UTC, pallabpain commented on riocli/organization/select.py
> +            "Please set your project with `rio project select PROJECT`".format(organization_name),
```suggestion
            "Please set your project with `rio project select PROJECT_NAME`".format(organization_name),
```

2024-01-18 04:34 UTC, pallabpain reviewed
Once you are ready with all the fixes, please discuss the commit messages before merging.

2024-01-19 10:38 UTC, pallabpain approved these changes

2024-01-19 11:41 UTC, smrutisenapati approved these changes

2024-01-19 11:42 UTC, merged