feat(deployment): adds support for host subpath uid/gid/perm
rapyuta-robotics/rapyuta-io-cli pull request #279
Opened 2024-02-22 10:08 UTC by amitsingh21

### Description
This PR supports specifying a device volume sub-path's uid, gid, and permissions. Please see the updated JSONSchema spec below
```yaml
  deviceVolumeAttachSpec:
    type: object
    properties:
      execName:
        type: string
      mountPath:
        type: string
        pattern: '^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$'
      subPath:
        type: string
        pattern: '^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$'
      uid:
        type: integer
      gid:
        type: integer
      perm:
        type: integer
    additionalProperties: false
```
### Depends
* https://github.com/rapyuta-robotics/rapyuta-io-sdk/pull/75

2024-02-22 17:33 UTC, pallabpain approved these changes

2024-02-26 14:12 UTC, ankitrgadiya requested changes

2024-02-26 14:12 UTC, ankitrgadiya commented on riocli/apply/manifests/deployment-nonros-device.yaml
> +      perm: 755 # permissions for subpath
suggestion: Consider marking these fields as optional so its clear that its not required.
```suggestion
      uid: 1000 # [Optional] userid for subpath
      gid: 1000 # [Optional] groupid for subpath
      perm: 755 # [Optional] permissions for subpath
```

2024-02-26 14:12 UTC, ankitrgadiya commented on riocli/jsonschema/schemas/deployment-schema.yaml
> +        default: 1000
@pallabpain Does this mean if the user does not specify then the default will become 1000? If so I think this is not desired then we can remove the default field.

2024-02-27 05:23 UTC, pallabpain requested changes

2024-02-27 05:23 UTC, pallabpain commented on riocli/deployment/model.py
> +                    perm = vol.perm if hasattr(vol, 'perm') else None
```suggestion
                    uid = getattr(vol, 'uid', None)
                    gid = getattr(vol, 'gid', None)
                    perm = getattr(vol, 'perm', None)
```

2024-02-27 05:42 UTC, ankitrgadiya approved these changes

2024-02-27 08:53 UTC, pallabpain approved these changes

2024-02-27 08:56 UTC, merged