chore: add support for custom configvariables and lables at the time …
rapyuta-robotics/rapyuta-io-cli pull request #323
Opened 2024-06-17 10:24 UTC by rrkumarshikhar

…of onboarding the device

2024-06-21 11:49 UTC, pallabpain commented
@rrkumarshikhar Is this ready for review?

2024-06-25 09:54 UTC, pallabpain requested changes

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +    def create_hwil_device(self) -> str:
todo: refactor and move these helper functions under `riocli/device/util.py` so that were can reuse them in `rio device create --virtual` command.

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +            return False
todo: add a comment explaining why this is needed.

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +        hwil_device = self.create_hwil_device()
nit: leave a blank line here.
```suggestion
        if not self.spec.get('virtual', {}).get('enabled', False):
            device = client.create_device(self.to_v1())
            return device
            
        hwil_device = self.create_hwil_device()
```

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +        click.secho("hwil device create successfully")
todo: remove these echo statements once testing is done.

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +        device_uuid = find_device_guid(client, self.metadata.name)
todo: handler this in a try-catch block.
```python
try:
    device_guid = find_device_guid(client, self.metadata.name)
    device = client.get_device(device_guid)
except DeviceNotFound as e:
    device = client.create_device(self.to_v1())
```

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +            sys.exit(code)
We don't have to do this here. Instead, if exit code is not 0, raise an exception.

2024-06-25 09:54 UTC, pallabpain commented on riocli/device/model.py
> +        return new_labels
todo: I believe this is yet to be implemented correctly.

2024-06-27 05:13 UTC, rrkumarshikhar commented
![image](https://github.com/rapyuta-robotics/rapyuta-io-cli/assets/91951664/1502dcad-f7b0-4a10-9c62-61ecf4f49a61)
these are the labels that are added in rapyuta-io-device

2024-06-27 05:24 UTC, rrkumarshikhar commented
![image](https://github.com/rapyuta-robotics/rapyuta-io-cli/assets/91951664/d106634b-0463-4d3d-8c8f-a331d647b33b)
this is the output while doing the rio apply command

2024-06-27 12:47 UTC, pallabpain requested changes
Mostly looks good. Minor comments. I'll verify the functionality while you address the comments.

2024-06-27 12:47 UTC, pallabpain commented on riocli/apply/manifests/device.yaml
> +    custom_label_3: label3
todo: update this example. labels go in metadata.

2024-06-27 12:47 UTC, pallabpain commented on riocli/device/util.py
> +    try:
nit: leave a blank line before this.

2024-06-27 12:47 UTC, pallabpain commented on riocli/device/util.py
> +def create_hwil_device(spec, metadata):
todo: type annotate this.

```suggestion
def create_hwil_device(spec: dict, metadata: dict) -> Munch:
```

2024-06-27 12:47 UTC, pallabpain commented on riocli/device/util.py
> +    return new_labels
```suggestion
    return {
        "user": user_email,
        "organization": organization_id,
        "project": project_id,
        "product": product_name,
        "rapyuta_device_name": device_name,
    }
```

2024-06-27 12:47 UTC, pallabpain commented on riocli/device/util.py
> +    organization_id = data.get('organization_id', None)
todo: for this operation, these values will be there. so we need not `.get` them.
```suggestion
    user_email = data['email_id']
    project_id = data['project_id']
    organization_id = data['organization_id']
```

2024-06-27 12:49 UTC, pallabpain commented
> ![image](https://private-user-images.githubusercontent.com/91951664/343640689-d106634b-0463-4d3d-8c8f-a331d647b33b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTI3NzIsIm5iZiI6MTcxOTQ5MjQ3MiwicGF0aCI6Ii85MTk1MTY2NC8zNDM2NDA2ODktZDEwNjYzNGItMDQ2My00ZDNkLThjOGYtYTMzMWQ2NDdiMzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEyNDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NjMyN2QwMGVjNDQ1N2U4ZWU3MmNhNGZhNWU5MTJmZDQ4NWZhMzdmMmVmODcwZDE2NTI5NDllZGIwOGQ2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k__52XuWOD4fqjNwQTcP7m-j2UaeqkHMr0NyNOkhcoQ) this is the output while doing the rio apply command


This should not be printed.
```
Creating hwil device ... 
```

2024-06-27 12:50 UTC, pallabpain requested changes

2024-06-27 12:50 UTC, pallabpain commented on riocli/device/util.py
> +            click.style(f'Creating hwil device with configuration = {os}:{codename}:{arch}', fg='cyan', bold=True))
todo: please remove secho and raise exception.

2024-06-27 12:50 UTC, pallabpain commented on riocli/device/util.py
> +        click.secho(f'Failed to create hwil device: {str(e)}', fg='red')
remove this.

2024-06-27 19:40 UTC, pallabpain requested changes
Minor comment. 

Please create a separate wrike ticket for implementing the delete flow. I couldn't clean up the device with `rio delete device.yaml`.

2024-06-27 19:40 UTC, pallabpain commented on riocli/apply/manifests/device.yaml
> +    highperf: True # Optional [Ture, False (default)]
nit: If someone copy-pastes this manifest, highperf should be set to False.
```suggestion
    highperf: False # Optional [True, False (default)]
```

2024-06-27 19:49 UTC, pallabpain commented on riocli/device/model.py
> +            return False
On a second thought, let's implement `update_object` and `delete_object` and get rid of this condition in a separate PR.

The update_object implementation can take care of re-onboarding.

2024-06-27 19:51 UTC, pallabpain approved these changes

2024-06-27 19:55 UTC, merged