feat(sort): generated manifest file
rapyuta-robotics/rapyuta-io-cli pull request #332
Opened 2024-07-05 02:14 UTC by dio-lee

2024-07-08 07:58 UTC, ankitrgadiya requested changes
The change looks good to me. @dio-lee Can you please update the commit message?
```
feat(template): sort rendered templates by file-name
```
ref: https://github.com/rapyuta-robotics/rapyuta_io/wiki/Contribution-Guidelines#git-hygiene

PS: Thanks for your contribution. We appreciate it.

2024-07-09 11:13 UTC, pallabpain approved these changes

2024-07-09 11:13 UTC, pallabpain commented
> The change looks good to me. @dio-lee Can you please update the commit message?
> 
> ```
> feat(template): sort rendered templates by file-name
> ```
> 
> ref: https://github.com/rapyuta-robotics/rapyuta_io/wiki/Contribution-Guidelines#git-hygiene
> 
> PS: Thanks for your contribution. We appreciate it.

@ankitrgadiya I think we can squash and merge with the PR title and description.

2024-07-11 07:25 UTC, ankitrgadiya approved these changes

2024-07-11 07:25 UTC, merged