feat(vpn): adds option to populate vpn peers in hosts file
rapyuta-robotics/rapyuta-io-cli pull request #356
Opened 2024-09-18 19:21 UTC by pallabpain

2024-09-19 09:31 UTC, ankitrgadiya requested changes

2024-09-19 09:31 UTC, ankitrgadiya commented on riocli/vpn/disconnect.py
> +def cleanup_hosts_file():
suggestion: Can we move the hosts file logic to util.py? Also, let's add the cleanup_hosts_file in `project select` and `auth login` commands as well.

2024-09-19 17:05 UTC, pallabpain commented
@ankitrgadiya As we discussed over the chat,
1. Updated the implementation to account for necessary privileged access. The code will effectively perform a `mv` on the temp hosts file to the default hosts file on the system.
2. The update_hosts_file helper cleans up the old entries, if present.
3. `rio auth login`, `rio project select` and `rio organization select` clean up the hosts file.
4. The clean up code will only write the file if entries are actually removed.

2024-10-09 11:53 UTC, ankitrgadiya approved these changes

2024-10-10 12:53 UTC, merged