feat(device): execute command on multiple devices
rapyuta-robotics/rapyuta-io-cli pull request #402
Opened 2024-12-12 07:21 UTC by pallabpain

### Description

### Testing
With `--async`
```
╭─ ~/Projects/python/rapyuta-robotics/rapyuta-io-cli on feat/exec-on-multiple-devices !2                     took 17s Py rapyuta-io-cli at 13:17:09
╰─❯ uv run rio device execute '.*' 'uname -a' --async
>>> 17098c40-5aec-42a7-bd4d-825bc72f4699: Success
Linux controller2 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
>>> f1677d7d-07c7-4877-905b-ef4dfe56426a: Success
Linux nuc-sn-btws24200glv 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
>>> e7ac3b0a-bdf1-4c8a-a4aa-f38187831ebd: Success
Linux edge2 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
Without `--async`
```
╭─ ~/Projects/python/rapyuta-robotics/rapyuta-io-cli on feat/exec-on-multiple-devices !2                     took 43s Py rapyuta-io-cli at 13:15:53
╰─❯ uv run rio device execute '.*' 'uname -a'        
>>> 17098c40-5aec-42a7-bd4d-825bc72f4699: Success
Linux controller2 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
>>> e7ac3b0a-bdf1-4c8a-a4aa-f38187831ebd: Success
Linux edge2 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
>>> f1677d7d-07c7-4877-905b-ef4dfe56426a: Success
Linux nuc-sn-btws24200glv 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
---
Fixes [AB#39696](https://dev.azure.com/rapyuta-robotics/3151e969-9eb7-4729-b4e8-8c659c416104/_workitems/edit/39696)

2025-03-05 05:24 UTC, ankitrgadiya requested changes

2025-03-05 05:24 UTC, ankitrgadiya commented on riocli/device/execute.py
> +            )
suggestion: Let's drop the ThreadPoolExecutor and use multiple device support from the SDK.

Use this branch from SDK: https://github.com/rapyuta-robotics/rapyuta-io-sdk/pull/105/files

2025-03-05 05:24 UTC, ankitrgadiya commented on riocli/device/execute.py
> +            )
We will have to parse the message correctly and print the output in this format.

2025-03-13 08:23 UTC, pallabpain commented on riocli/device/execute.py
> +    cmd = " ".join(command)
Consider using `shlex.join` here.
https://docs.python.org/3/library/shlex.html#shlex.join

2025-03-13 08:23 UTC, pallabpain commented on riocli/device/execute.py
> +    colums, _ = get_terminal_size()
typo: `columns`

Also, this isn't used in the code.

2025-03-20 08:58 UTC, ankitrgadiya approved these changes

2025-03-20 09:02 UTC, ankitrgadiya commented
Waiting on the Backend Fix: https://github.com/rapyuta-robotics/device_manager/pull/355

2025-03-24 06:17 UTC, merged